name: flutter_country_code
description: Flexible Country picker for getting Country code and Calling code.
version: 2.0.0
homepage: https://github.com/mustafa-707/flutter_country_code.git

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  sim_card_code: ^0.0.2
  phone_numbers_parser: ^8.3.0
  flutter_libphonenumber: ^2.2.3
  dartarabic: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - flags/
