name: country_code_helper
description: Flexible Country picker for getting Country code and Calling code.
version: 0.1.2
repository: https://github.com/mustafa-707/flutter_country_code
issue_tracker: https://github.com/mustafa-707/flutter_country_code/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  sim_card_code: ^0.0.2
  phone_numbers_parser: ^9.0.1
  flutter_libphonenumber: ^2.5.0
  dartarabic: ^0.1.2


flutter:
  uses-material-design: true
  assets:
    - flags/
