name: country_code_helper
description: Flexible Country picker for getting Country code and Calling code.
version: 0.2.4
repository: https://github.com/mustafa-707/country_code_helper
issue_tracker: https://github.com/mustafa-707/country_code_helper/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  sim_card_code: ^0.0.9
  phone_numbers_parser: ^9.0.3
  flutter_libphonenumber: ^2.5.1
  dartarabic: ^0.3.1

flutter:
  uses-material-design: true
  assets:
    - flags/
