name: flutter_country_code
description: Flexible Country picker for getting Country code and Calling code.
version: 1.0.3
homepage: https://github.com/mustafa-707/flutter_country_code.git

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_sim_country_code: ^0.1.2
  meta: ^1.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        package: com.example.flutter_country_code
        pluginClass: PhoneNumberPlugin
      ios:
        pluginClass: PhoneNumberPlugin  
  assets:
    - flags/
    - raw/
