name: flutter_country_code
description: Flexible Country picker for getting Country code and Calling code.
version: 1.0.0
homepage: https://github.com/mustafa-707/flutter_country_code.git

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_sim_country_code: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - flags/
    - raw/
